FROM node:16 AS backend
WORKDIR /root

# First cache the node_modules
COPY ["backend/package.json", "package.json"]
COPY ["backend/package-lock.json", "package-lock.json"]
RUN npm ci --unsafe-perm

# Then copy all the files needed for tests (almost everything)
COPY ["backend/", ""]
