# Ubuntu is required to run image on ARM64 processor such as Apple M1 chips
# This limitation is due to available binaries of Mongodb.
#FROM sitespeedio/node:ubuntu-20.04-nodejs-16.16.0 AS backend
FROM node:20 AS backend
WORKDIR /root

# First cache the node_modules
COPY ["backend/package.json", "package.json"]
COPY ["backend/package-lock.json", "package-lock.json"]
RUN npm ci --unsafe-perm

# Then copy all the files needed for tests (almost everything)
COPY ["backend/", ""]
