version: "3"
services:
  web:
    build: .
    # image: $LOCAL_IMAGE_ID
    # Mount and run tests.
    volumes:
      - ./tests:/tests
    command: ["sh", "-c", "cd backend && npm install && npm test"]
