pr: none
trigger:
  branches:
    include:
      - main
      - revert-frontend-break

variables:
  - group: elarande-general-params
  - group: elarande-spoke1-ref
  - name: dockerfilePath
    value: "$(Pipeline.Workspace)/github/Dockerfile"
  - name: appName
    value: scanned-exams-ref
  - name: imageName
    value: scanned-exams
  - name: tag
    value: "${BUILD_BUILDNUMBER}_${BUILD_SOURCEVERSION:0:4}"
  - name: parametersFileName
    value: ref.parameters.json

resources:
  repositories:
    - repository: cet-iac
      type: git
      name: Cloud Excellence Team/cet-iac
      ref: main

pool:
  vmImage: "ubuntu-latest"

steps:
  - template: templates/docker/build.yml@cet-iac
    parameters:
      runScan: false
      dockerFilePath: $(dockerfilePath)
      imageName: $(imageName)
      tag: $(tag)

  - task: Npm@1
    displayName: "Run `npm ci` for testing backend"
    inputs:
      workingDir: "$(Pipeline.Workspace)/github/backend"
      command: "ci"

  - task: Npm@1
    displayName: "Test backend"
    inputs:
      workingDir: "$(Pipeline.Workspace)/github/backend"
      command: "custom"
      customCommand: "test"

  - template: templates/docker/push.yml@cet-iac
    parameters:
      dockerFilePath: $(dockerfilePath)
      imageName: $(imageName)
      tag: $(tag)

  - template: templates/app-service/update-image.yml@cet-iac
    parameters:
      parametersFileName: $(parametersFileName)
      appName: $(appName)
      imageName: $(imageName)
      tag: $(tag)
      isApi: false
      hasSlot: false
